import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Header from './components/layout/Header'
import AppsNameProvider from './components/layout/Context'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yunohost for Everyone',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <AppsNameProvider>
          <body className={montserrat.className}>
            <Header />
            {children}
          </body>
        </AppsNameProvider>
      </html>
  )
}
